alias ll='ls -la'
alias lt='ls --human-readable --size -1 -S --classify'
alias nrebuild='sudo nixos-rebuild --use-remote-sudo switch'
alias code='codium'
alias rgf='rg --files | rg'
alias rcd='ranger'